name: macro_global_task
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  stacked: ^3.2.1
  stacked_services: ^1.0.2
  logger: ^1.3.0
  animated_splash_screen: ^1.3.0
  lottie: ^2.3.2
  flutter_signin_button: ^2.0.0
  image_picker: ^0.8.7+3
  firebase_auth: ^4.4.1
  google_sign_in: ^6.1.0
  build_runner: ^2.1.2
  dio: ^5.0.3
  dio_cookie_manager: ^2.0.0
  retrofit: ^4.0.1
  json_annotation: ^4.1.0
  retrofit_generator: ^6.0.0+1
  cookie_jar: ^3.0.1
  json_serializable: ^6.6.1
  shared_preferences: ^2.1.0
  flutter_launcher_icons: ^0.13.0
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"



flutter:

  
  uses-material-design: true

 
  assets:
    - assets/splash_logo.json
    - assets/login_logo.png
    
     

 